"""Image converter for manual mode"""

import os
from pathlib import Path
from typing import Dict, Any

import ffmpeg

from .base_converter import BaseConverter
from ..config.codec_config import get_image_quality_config
from client.core.ffmpeg_utils import get_image_dimensions, run_ffmpeg_hidden
from client.core.tool_registry import get_ffmpeg_path


class ImageConverter(BaseConverter):
    """
    Handles image conversion in manual mode
    
    Supports: JPG, PNG, WebP, AVIF, TIFF, BMP
    Applies: Quality, Resize, Rotation, Aspect Ratio presets
    """
    
    SUPPORTED_FORMATS = {'.jpg', '.jpeg', '.png', '.webp', '.avif', '.tiff', '.bmp'}
    
    def get_supported_extensions(self) -> set:
        return self.SUPPORTED_FORMATS
    
    def convert(self, file_path: str, output_path: str) -> bool:
        """
        Convert image using FFmpeg
        
        Args:
            file_path: Source image path (absolute)
            output_path: Output image path (absolute, generated by SuffixManager)
            
        Returns:
            True if successful, False otherwise
        """
        try:
            # Ensure output directory exists
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            
            # Emit progress start (blue bar)
            self.emit_progress(0.0)
            
            # Build FFmpeg pipeline
            stream = self._build_filter_chain(file_path)
            output_args = self._get_output_args()
            
            output = ffmpeg.output(stream, output_path, **output_args)
            
            if self.params.get('overwrite', False):
                output = ffmpeg.overwrite_output(output)
            
            # Execute with specified FFmpeg binary
            self.emit_status(f"Converting: {Path(file_path).name}")
            
            # Get FFmpeg path from centralized source (respects Advanced Settings)
            ffmpeg_cmd = get_ffmpeg_path()
            
            # Run FFmpeg
            run_ffmpeg_hidden(output, cmd=ffmpeg_cmd, quiet=True)
            
            # Emit progress complete (blue bar)
            self.emit_progress(1.0)
            self.emit_status(f"[OK] {Path(output_path).name}")
            return True
            
        except ffmpeg.Error as e:
            error_msg = e.stderr.decode('utf-8') if e.stderr else str(e)
            self.emit_status(f"FFmpeg error: {error_msg[:200]}")
            print(f"Image conversion FFmpeg error for {file_path}: {error_msg}")
            return False
        except Exception as e:
            self.emit_status(f"Conversion error: {str(e)}")
            print(f"Image conversion error for {file_path}: {str(e)}")
            import traceback
            traceback.print_exc()
            return False
    
    def _build_filter_chain(self, file_path: str):
        """
        Build FFmpeg filter chain from UI parameters
        
        Order: Resize → Rotation → Aspect Ratio
        """
        stream = ffmpeg.input(file_path)
        
        # 1. Apply resize (if current_resize is set)
        current_resize = self.params.get('current_resize')
        if current_resize:
            stream = self._apply_resize(stream, file_path, current_resize)
        
        # 2. Apply rotation
        rotation = self.params.get('rotation_angle', 'No rotation')
        if rotation != 'No rotation':
            stream = self._apply_rotation(stream, rotation)
        
        # 3. Apply aspect ratio preset (Instagram, 1:1, etc.)
        aspect_ratio = self.params.get('image_preset_ratio')
        is_instagram = self.params.get('image_preset_social') == 'Instagram'
        if is_instagram or aspect_ratio:
            target_ratio = aspect_ratio or ('9:16' if is_instagram else None)
            if target_ratio:
                stream = self._apply_aspect_ratio(stream, target_ratio)
        
        return stream
    
    def _apply_resize(self, stream, file_path: str, resize_value: str):
        """
        Apply resize filter based on resize value format
        
        Supports:
        - Width in pixels: "1920"
        - Percentage: "50%"
        - Longer edge: "L1920"
        """
        if not resize_value or resize_value == 'No resize':
            return stream
        
        # Percentage resize
        if isinstance(resize_value, str) and resize_value.endswith('%'):
            percent = float(resize_value[:-1]) / 100.0
            return ffmpeg.filter(stream, 'scale', f'iw*{percent}', f'ih*{percent}')
        
        # Longer edge resize (no upscaling)
        if isinstance(resize_value, str) and resize_value.startswith('L'):
            target_longer_edge = int(resize_value[1:])
            orig_w, orig_h = get_image_dimensions(file_path)
            longer_edge = max(orig_w, orig_h)
            
            # Don't upscale if image is already smaller
            if longer_edge < target_longer_edge:
                return stream
            
            if orig_w > orig_h:
                # Width is longer
                return ffmpeg.filter(stream, 'scale', target_longer_edge, -1)
            else:
                # Height is longer - calculate width to maintain aspect ratio
                ratio = target_longer_edge / orig_h
                new_w = int(orig_w * ratio)
                new_w = new_w if new_w % 2 == 0 else new_w - 1  # Ensure even
                return ffmpeg.filter(stream, 'scale', new_w, target_longer_edge)
        
        # Width-based resize (maintain aspect ratio)
        width = int(resize_value)
        return ffmpeg.filter(stream, 'scale', width, -1)
    
    def _apply_rotation(self, stream, rotation: str):
        """
        Apply rotation filter
        
        Supported: 90° clockwise, 180°, 270° clockwise
        """
        if rotation == '90° clockwise':
            return ffmpeg.filter(stream, 'transpose', 1)
        elif rotation == '180°':
            stream = ffmpeg.filter(stream, 'transpose', 2)
            stream = ffmpeg.filter(stream, 'transpose', 2)
            return stream
        elif rotation == '270° clockwise':
            return ffmpeg.filter(stream, 'transpose', 2)
        
        return stream
    
    def _apply_aspect_ratio(self, stream, ratio: str):
        """
        Apply aspect ratio preset with padding
        
        Scales to fit ratio, then pads with black bars
        """
        ratio_dimensions = {
            '4:3': (1440, 1080),
            '1:1': (1080, 1080),
            '16:9': (1920, 1080),
            '9:16': (1080, 1920)
        }
        
        if ratio in ratio_dimensions:
            tw, th = ratio_dimensions[ratio]
            # Scale to fit (decrease only, no upscaling)
            stream = ffmpeg.filter(
                stream, 'scale', tw, th,
                force_original_aspect_ratio='decrease'
            )
            # Pad to exact dimensions
            stream = ffmpeg.filter(stream, 'pad', tw, th, '(ow-iw)/2', '(oh-ih)/2')
        
        return stream
    
    def _get_output_args(self) -> Dict[str, Any]:
        """
        Build FFmpeg output arguments based on format and quality
        
        Returns:
            Dict of FFmpeg output parameters
        """
        format_type = self.get_format_extension()
        quality = self.params.get('quality', 85)
        
        config = get_image_quality_config(format_type)
        args = {}
        
        if format_type in ['jpg', 'jpeg']:
            # FFmpeg q:v scale is 1-31 (1=best, 31=worst)
            # UI quality is 0-100 (100=best)
            qscale_range = config['qscale_max'] - config['qscale_min']
            qscale = config['qscale_max'] - int((quality / 100.0) * qscale_range)
            args['q:v'] = max(config['qscale_min'], min(config['qscale_max'], qscale))
        
        elif format_type == 'png':
            # PNG compression level 0-9 (0=none, 9=max compression)
            # Higher UI quality = less compression
            compression = int((1 - quality / 100.0) * config['compression_max'])
            args['compression_level'] = max(0, min(9, compression))
        
        elif format_type == 'webp':
            # WebP quality 0-100 (direct mapping)
            args['quality'] = quality
        
        elif format_type == 'avif':
            # AVIF uses CRF 0-63 (lower=better quality)
            # UI quality 0-100 (higher=better) → CRF 63-0 (inverted)
            crf = int(63 - (quality / 100.0) * 63)
            args['c:v'] = 'libsvtav1'
            args['crf'] = max(0, min(63, crf))
            
            # Heavy compression toggle
            heavy_compression = self.params.get('heavy_compression', False)
            args['preset'] = 4 if heavy_compression else 6
            args['still-picture'] = 1  # Critical for single-frame optimization
        
        return args
