"""Video converter for manual mode"""

import os
from pathlib import Path
from typing import Dict, Any, Optional

import ffmpeg

from .base_converter import BaseConverter
from ..config.codec_config import get_video_codec_config, VIDEO_CODECS
from client.core.ffmpeg_utils import get_video_dimensions
from client.core.tool_registry import get_ffmpeg_path


def get_video_duration(file_path: str) -> float:
    """Get video duration in seconds using ffprobe"""
    try:
        from client.core.tool_registry import get_ffprobe_path
        probe = ffmpeg.probe(file_path, cmd=get_ffprobe_path())
        return float(probe['format'].get('duration', 0))
    except Exception:
        return 0


def has_audio_stream(file_path: str) -> bool:
    """Check if video has audio stream"""
    try:
        from client.core.tool_registry import get_ffprobe_path
        probe = ffmpeg.probe(file_path, cmd=get_ffprobe_path())
        return any(s.get('codec_type') == 'audio' for s in probe.get('streams', []))
    except Exception:
        return False


class VideoConverter(BaseConverter):
    """
    Handles video conversion in manual mode
    
    Supports: MP4, WebM, MKV, AVI, MOV, etc.
    Applies: Codec selection, Quality (CRF), Resize, Rotation, Time cutting, Retime
    """
    
    SUPPORTED_FORMATS = {
        '.mp4', '.webm', '.mkv', '.avi', '.mov', '.wmv', 
        '.flv', '.m4v', '.3gp', '.ts', '.mts', '.m2ts'
    }
    
    # Codec name mapping from UI to internal codec key
    CODEC_MAP = {
        "MP4 (H.264)": "h264",
        "MP4 (H.265)": "h265",
        "MP4 (AV1)": "av1",
        "WebM (VP9)": "vp9",
        "WebM (AV1)": "av1_webm",
        # Legacy/Fallback mappings
        "H.264": "h264",
        "H.265": "h265", 
        "VP9": "vp9",
        "AV1": "av1"
    }
    
    def get_supported_extensions(self) -> set:
        return self.SUPPORTED_FORMATS
    
    def convert(self, file_path: str, output_path: str) -> bool:
        """
        Convert video using FFmpeg
        
        Args:
            file_path: Source video path (absolute)
            output_path: Output video path (absolute, generated by SuffixManager)
            
        Returns:
            True if successful, False otherwise
        """
        try:
            # Ensure output directory exists
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            
            # Get codec configuration
            selected_codec = self.params.get('codec', 'H.264 (MP4)')
            codec_key = self.CODEC_MAP.get(selected_codec, 'h264')
            codec_config = get_video_codec_config(codec_key)
            
            if not codec_config:
                self.emit_status(f"Unknown codec: {selected_codec}")
                return False
            
            self.emit_status(f"Converting: {Path(file_path).name}")
            print(f"[VideoConverter] Converting with codec: {codec_config.name}")
            
            # Build input with optional time cutting
            input_args = self._get_input_args(file_path)
            input_stream = ffmpeg.input(file_path, **input_args)
            video_stream = input_stream.video
            
            # Check for audio
            audio_exists = has_audio_stream(file_path)
            audio_stream = input_stream.audio if audio_exists else None
            
            # Apply retime (speed change)
            video_stream, audio_stream = self._apply_retime(video_stream, audio_stream)
            
            # Apply resize
            video_stream = self._apply_resize(video_stream, file_path)
            
            # Apply rotation
            video_stream = self._apply_rotation(video_stream)
            
            # Build output arguments
            output_args = self._build_output_args(codec_config, audio_exists)
            
            # Create output stream
            if audio_stream is not None and codec_config.audio_codec:
                output = ffmpeg.output(video_stream, audio_stream, output_path, **output_args)
            else:
                output = ffmpeg.output(video_stream, output_path, **output_args)
            
            if self.params.get('overwrite', False):
                output = ffmpeg.overwrite_output(output)
            
            # Get FFmpeg path from centralized source
            ffmpeg_cmd = get_ffmpeg_path()
            
            # Get video duration for progress tracking
            total_duration = get_video_duration(file_path)
            
            # Apply time cutting adjustments to duration
            if self.params.get('enable_time_cutting'):
                time_start = self.params.get('time_start', 0)
                time_end = self.params.get('time_end', 1)
                total_duration = total_duration * (time_end - time_start)
            
            # Apply retime adjustments to duration
            if self.params.get('retime_enabled') or self.params.get('enable_retime'):
                retime_speed = self.params.get('retime_speed', 1.0)
                if retime_speed and retime_speed > 0:
                    total_duration = total_duration / retime_speed
            
            # Run FFmpeg with progress tracking
            print(f"[VideoConverter] FFmpeg command: {ffmpeg_cmd}")
            print(f"[VideoConverter] Total duration for progress: {total_duration:.2f}s")
            
            # Use progress tracking for video (has duration)
            if total_duration > 0 and self.progress_callback:
                success = self.run_ffmpeg_with_progress(output, ffmpeg_cmd, total_duration)
            else:
                # Fallback to standard run
                ffmpeg.run(
                    output,
                    cmd=ffmpeg_cmd,
                    capture_stdout=True,
                    capture_stderr=True,
                    quiet=True
                )
                success = True
            
            if success:
                self.emit_status(f"[OK] {Path(output_path).name}")
                return True
            else:
                return False
            
        except ffmpeg.Error as e:
            error_msg = e.stderr.decode('utf-8') if e.stderr else str(e)
            
            # Check for GPU error and attempt fallback
            from client.utils.gpu_detector import get_gpu_detector
            gpu_detector = get_gpu_detector(get_ffmpeg_path())
            
            # Check if this error looks like a GPU failure (Codec not supported, etc)
            if gpu_detector.is_gpu_error(error_msg) or "Codec not supported" in error_msg:
                print(f"[VideoConverter] Detected GPU error: {error_msg[:100]}...")
                self.emit_status("GPU encoding failed, attempting CPU fallback...")
                
                # Verify we haven't already fallen back (avoid infinite loop)
                codec_config = get_video_codec_config(codec_key)
                if codec_config and self._attempt_fallback_conversion(file_path, output_path, codec_config, audio_exists):
                    return True
            
            self.emit_status(f"FFmpeg error: {error_msg[:200]}")
            print(f"Video conversion FFmpeg error for {file_path}: {error_msg}")
            return False
        except Exception as e:
            self.emit_status(f"Conversion error: {str(e)}")
            print(f"Video conversion error for {file_path}: {str(e)}")
            import traceback
            traceback.print_exc()
            return False
    
    def _attempt_fallback_conversion(self, file_path: str, output_path: str, original_config, audio_exists: bool) -> bool:
        """
        Attempt conversion using CPU fallback when GPU encoder fails.
        """
        try:
            from client.utils.gpu_detector import get_gpu_detector
            detector = get_gpu_detector(get_ffmpeg_path())
            
            # Get fallback encoder name (usually libsvtav1, libx264, etc)
            fallback_encoder, _ = detector.get_fallback_encoder(original_config.ffmpeg_codec)
            print(f"[VideoConverter] Fallback: {original_config.ffmpeg_codec} -> {fallback_encoder}")
            
            if fallback_encoder == original_config.ffmpeg_codec:
                print("[VideoConverter] Fallback encoder same as original, aborting.")
                return False
                
            # Create a modified config for the fallback
            from dataclasses import replace
            
            # Clean extra args (remove GPU specific ones)
            clean_extra = {}
            # Allow CPU-specific args
            cpu_args = {'cpu-used', 'crf', 'preset', 'tune'} 
            
            # Add fallback specific args
            fallback_params = detector.get_encoder_params(fallback_encoder, self.params.get('quality', 85))
            for k, v in fallback_params.items():
                if k == 'crf': continue # Handled by build_output_args
                if k == 'preset': continue # Handled by config.preset
                clean_extra[k] = v
                
            # Update config with fallback encoder
            fallback_config = replace(
                original_config,
                ffmpeg_codec=fallback_encoder,
                extra_args=clean_extra,
                preset=fallback_params.get('preset', 'medium')
            )
            
            print(f"[VideoConverter] Retrying with: {fallback_encoder}")
            self.emit_status(f"Retrying with CPU ({fallback_encoder})...")
            
            # --- Re-build Pipeline (Duplicated from convert) ---
            
            # Build input
            input_args = self._get_input_args(file_path)
            input_stream = ffmpeg.input(file_path, **input_args)
            video_stream = input_stream.video
            audio_stream = input_stream.audio if audio_exists else None
            
            # Apply filters
            video_stream, audio_stream = self._apply_retime(video_stream, audio_stream)
            video_stream = self._apply_resize(video_stream, file_path)
            video_stream = self._apply_rotation(video_stream)
            
            # Build output args with FALLBACK config
            output_args = self._build_output_args(fallback_config, audio_exists)
            
            # Create output stream
            if audio_stream is not None and fallback_config.audio_codec:
                output = ffmpeg.output(video_stream, audio_stream, output_path, **output_args)
            else:
                output = ffmpeg.output(video_stream, output_path, **output_args)
            
            if self.params.get('overwrite', False):
                output = ffmpeg.overwrite_output(output)
                
            ffmpeg_cmd = get_ffmpeg_path()
            
            # Recalculate duration
            total_duration = get_video_duration(file_path)
            if self.params.get('enable_time_cutting'):
                time_start = self.params.get('time_start', 0)
                time_end = self.params.get('time_end', 1)
                total_duration = total_duration * (time_end - time_start)
            if self.params.get('retime_enabled') or self.params.get('enable_retime'):
                retime_speed = self.params.get('retime_speed', 1.0)
                if retime_speed > 0:
                    total_duration = total_duration / retime_speed
            
            # Run fallback
            if total_duration > 0 and self.progress_callback:
                success = self.run_ffmpeg_with_progress(output, ffmpeg_cmd, total_duration)
            else:
                ffmpeg.run(output, cmd=ffmpeg_cmd, capture_stdout=True, capture_stderr=True, quiet=True)
                success = True
                
            if success:
                self.emit_status(f"[OK] Converted with fallback")
                return True
                
            return False
            
        except Exception as e:
            print(f"[VideoConverter] Fallback failed: {e}")
            return False
    
    def _get_input_args(self, file_path: str) -> Dict[str, Any]:
        """Build input arguments including time cutting"""
        input_args = {}
        
        enable_time_cutting = self.params.get('enable_time_cutting', False)
        if enable_time_cutting:
            time_start = self.params.get('time_start')
            time_end = self.params.get('time_end')
            
            if time_start is not None and time_end is not None and time_start < time_end:
                video_duration = get_video_duration(file_path)
                if video_duration > 0:
                    start_time = time_start * video_duration
                    end_time = time_end * video_duration
                    input_args['ss'] = start_time
                    input_args['to'] = end_time
                    self.emit_status(f"Time cut: {start_time:.1f}s - {end_time:.1f}s")
        
        return input_args
    
    def _apply_retime(self, video_stream, audio_stream):
        """Apply speed change (retime) to video and audio streams"""
        retime_enabled = self.params.get('retime_enabled') or self.params.get('enable_retime')
        retime_speed = self.params.get('retime_speed', 1.0)
        
        if not retime_enabled or not retime_speed or retime_speed == 1.0:
            return video_stream, audio_stream
        
        try:
            speed = float(retime_speed)
            speed = max(0.1, min(3.0, speed))  # Clamp to valid range
            
            self.emit_status(f"Retime: {speed:.2f}x")
            
            # Apply to video
            video_stream = video_stream.filter('setpts', f'PTS/{speed}')
            
            # Apply to audio if present
            if audio_stream is not None:
                try:
                    if speed <= 2.0:
                        audio_stream = audio_stream.filter('atempo', speed)
                    else:
                        # Chain atempo filters for speeds > 2x
                        audio_stream = audio_stream.filter('atempo', 2.0).filter('atempo', speed / 2.0)
                except Exception:
                    audio_stream = None  # Skip audio on error
            
            return video_stream, audio_stream
            
        except Exception as e:
            print(f"[VideoConverter] Retime error: {e}")
            return video_stream, audio_stream
    
    def _apply_resize(self, stream, file_path: str):
        """Apply resize filter based on params"""
        current_resize = self.params.get('current_resize')
        
        if not current_resize or current_resize == 'No resize':
            return stream
        
        # Percentage resize - use trunc to ensure even dimensions
        if isinstance(current_resize, str) and current_resize.endswith('%'):
            percent = float(current_resize[:-1]) / 100.0
            # Use trunc(x/2)*2 to ensure even dimensions
            return ffmpeg.filter(stream, 'scale', 
                w=f'trunc(iw*{percent}/2)*2', h=f'trunc(ih*{percent}/2)*2')
        
        # Longer edge resize (no upscaling)
        if isinstance(current_resize, str) and current_resize.startswith('L'):
            target_longer_edge = int(current_resize[1:])
            # Ensure target is even
            target_longer_edge = target_longer_edge - (target_longer_edge % 2)
            try:
                orig_w, orig_h = get_video_dimensions(file_path)
                longer_edge = max(orig_w, orig_h)
                
                if longer_edge < target_longer_edge:
                    return stream  # Don't upscale
                
                if orig_w > orig_h:
                    # Width is longer - scale width, auto height with even dims
                    return ffmpeg.filter(stream, 'scale', w=target_longer_edge, h=-2)
                else:
                    # Height is longer - auto width, scale height with even dims
                    return ffmpeg.filter(stream, 'scale', w=-2, h=target_longer_edge)
            except Exception:
                return stream
        
        # Width-based resize (maintain aspect ratio, even dimensions)
        try:
            width = int(current_resize)
            # Ensure width is even
            width = width - (width % 2)
            return ffmpeg.filter(stream, 'scale', w=width, h=-2)
        except ValueError:
            return stream
    
    def _apply_rotation(self, stream):
        """Apply rotation filter"""
        rotation = self.params.get('rotation_angle', 'No rotation')
        
        if rotation == '90° clockwise':
            return ffmpeg.filter(stream, 'transpose', 1)
        elif rotation == '180°':
            stream = ffmpeg.filter(stream, 'transpose', 2)
            return ffmpeg.filter(stream, 'transpose', 2)
        elif rotation == '270° clockwise':
            return ffmpeg.filter(stream, 'transpose', 2)
        
        return stream
    
    def _build_output_args(self, codec_config, has_audio: bool) -> Dict[str, Any]:
        """Build FFmpeg output arguments based on codec config and params"""
        encoder = codec_config.ffmpeg_codec
        output_args = {
            'vcodec': encoder,
            'f': codec_config.container,
        }
        
        # Set pixel format
        if codec_config.pixel_format:
            output_args['pix_fmt'] = codec_config.pixel_format
        
        # Apply quality - hardware encoders use different params than CRF
        quality = self.params.get('quality', 85)
        crf = codec_config.ui_quality_to_crf(quality)
        
        if encoder.endswith('_nvenc'):
            # NVENC: use -cq (constant quality) and VBR rate control
            output_args['cq'] = crf
            output_args['rc'] = 'vbr'
            print(f"[VideoConverter] Quality {quality} -> CQ {crf} (NVENC)")
        elif encoder.endswith('_qsv'):
            # QSV: use -global_quality
            output_args['global_quality'] = crf
            print(f"[VideoConverter] Quality {quality} -> global_quality {crf} (QSV)")
        elif encoder.endswith('_amf'):
            # AMF: use -qp_i and -qp_p
            output_args['rc'] = 'cqp'
            output_args['qp_i'] = crf
            output_args['qp_p'] = crf
            print(f"[VideoConverter] Quality {quality} -> QP {crf} (AMF)")
        else:
            # CPU software encoder: use CRF
            output_args['crf'] = crf
            print(f"[VideoConverter] Quality {quality} -> CRF {crf}")
        
        # Apply dynamic preset (speed/quality mapping) if available
        # This maps the quality slider to encoding speed (0=Fast/Draft, 100=Slow/Best)
        dynamic_preset = codec_config.ui_quality_to_preset(quality)
        if dynamic_preset and codec_config.preset_param:
            output_args[codec_config.preset_param] = dynamic_preset
            print(f"[VideoConverter] Dynamic preset: {codec_config.preset_param}={dynamic_preset}")
        elif codec_config.preset:
            # Fallback to static preset
            output_args['preset'] = codec_config.preset
        
        # Apply codec-specific extra args
        for key, value in codec_config.extra_args.items():
            output_args[key] = value
        
        # Handle audio
        if codec_config.container == 'webm':
            # WebM: typically no audio in this app
            output_args['an'] = None
        elif has_audio and codec_config.audio_codec:
            output_args['acodec'] = codec_config.audio_codec
            output_args['b:a'] = codec_config.audio_bitrate
        else:
            output_args['an'] = None
        
        return output_args
    
    def get_format_extension(self) -> str:
        """Get output format extension based on selected codec"""
        selected_codec = self.params.get('codec', 'H.264 (MP4)')
        codec_key = self.CODEC_MAP.get(selected_codec, 'h264')
        codec_config = get_video_codec_config(codec_key)
        
        if codec_config:
            return codec_config.container
        return 'mp4'
